version: '3.9'
services:
  app:
    build: .
    image: local-aws-console:latest
    container_name: local-aws-console
    ports:
      - '8080:8080'
    volumes:
      - $HOME/.aws:/root/.aws
      - ./config:/app/config
    environment:
      - NODE_ENV=production
      - VITE_PORT=8080
      